BEGIN TRANSACTION;

INSERT INTO public.users (username, password_hash, role) VALUES ('max', '$2a$10$kXnAbYWckcphV6uVqAtivutGkAgpPLIdCQGd.h/AtOiRZ8DW/u9w2', 'ROLE_PREMIUM');

INSERT INTO public.comic_data (upc, issue_number, series, publish_date, image_url, author, artist) VALUES (75960608936900111, 1, 'The Amazing Spider-Man (2018)', '07/11/2018', 'b/90/5b3feb60f1a30', 'Nick Spencer', 'Ryan Ottley');
INSERT INTO public.comic_data (upc, issue_number, series, publish_date, image_url, author, artist) VALUES (75960607913100111, 1, 'Thor: God of Thunder (2012)', '11/14/2012', '3/30/51646f6c2a712', 'Jason Aaron', 'Esad Ribic');
INSERT INTO public.comic_data (upc, issue_number, series, publish_date, image_url, author, artist) VALUES (75960609724103011, 30, 'Star Wars: Doctor Aphra (2020)', '04/12/2023', '3/70/64346a94258aa', 'Alyssa Wong', 'Rachael Stott');
INSERT INTO public.comic_data (upc, issue_number, series, publish_date, image_url, author, artist) VALUES (75960608956700111, 1, 'Immortal Hulk (2018)', '06/06/2018', '3/50/5b0f16d976240', 'Al Ewing', 'Joe Bennett');
INSERT INTO public.comic_data (upc, issue_number, series, publish_date, image_url, author, artist) VALUES (75960605921800111, 1, 'Civil War (2006)', '05/03/2006', 'e/f0/511307b2f1200', 'Mark Millar', 'Steve Mcniven');
INSERT INTO public.comic_data (upc, issue_number, series, publish_date, image_url, author, artist) VALUES (75960608857706111, 61, 'Avengers (2018)', '10/19/2022', '6/00/634f64cc2305b', 'Jason Aaron', 'Ivan Fiorelli');
INSERT INTO public.comic_data (upc, issue_number, series, publish_date, image_url, author, artist) VALUES (75960608917800311, 3, 'Ant-Man & the Wasp (2018)', '07/04/2018', '6/e0/5b3408e8c6a88', 'Mark Waid', 'Javier Garron');
INSERT INTO public.comic_data (upc, issue_number, series, publish_date, image_url, author, artist) VALUES (75960620099300511, 5, 'Death of Doctor Strange (2021)', '01/26/2022', '5/b0/61cf40567ca00', 'Jed Mackay', 'Lee Garbett');
INSERT INTO public.comic_data (upc, issue_number, series, publish_date, image_url, author, artist) VALUES (5960604716-64821, 648, 'Amazing Spider-Man (1999)', '11/10/2010', '6/03/5813b47f01394', 'Dan Slott', 'Humberto Ramos');
INSERT INTO public.comic_data (upc, issue_number, series, publish_date, image_url, author, artist) VALUES (75960605921800111, 1, 'Avengers Vs. X-Men (2012)', '04/04/2012', 'd/90/4f7dc878b57fe', 'Brian Michael Bendis', 'John Romita');
INSERT INTO public.comic_data (upc, issue_number, series, publish_date, image_url, author, artist) VALUES (75960608857706311, 63, 'Avengers (2018)', '12/07/2022', 'c/60/63863d3bdf1dc', 'Jason Aaron', 'Javier Garron');
INSERT INTO public.comic_data (upc, issue_number, series, publish_date, image_url, author, artist) VALUES (75960608857705911, 59, 'Avengers (2018)', '08/10/2022', 'c/90/62ed83c16d4fd', 'Jason Aaron', 'Javier Garron');
INSERT INTO public.comic_data (upc, issue_number, series, publish_date, image_url, author, artist) VALUES (75960608857705511, 55, 'Avengers (2018)', '04/20/2022', '9/f0/6259cb69b2ec8', 'Jason Aaron', 'Javier Garron');
INSERT INTO public.comic_data (upc, issue_number, series, publish_date, image_url, author, artist) VALUES (75960608857706611, 66, 'Avengers (2018)', '03/08/2023', 'a/40/63f4e9472ff8a', 'Jason Aaron', 'Javier Garron');
INSERT INTO public.comic_data (upc, issue_number, series, publish_date, image_url, author, artist) VALUES (75960608857706011, 60, 'Avengers (2018)', '12/07/2022', '6/40/631b39c245d7b', 'Mark Russell', 'Greg Land');
INSERT INTO public.comic_data (upc, issue_number, series, publish_date, image_url, author, artist) VALUES (759606094661001711, 17, 'X-Men (2019)', '01/27/2021', 'c/03/6009ea0295688', 'Jonathan Hickman', 'Brett Booth');
INSERT INTO public.comic_data (upc, issue_number, series, publish_date, image_url, author, artist) VALUES (759606094661002111, 21, 'X-Men (2019)', '06/09/2021', '9/00/60afe250e1e29', 'Jonathan Hickman', 'Nick Dragotta');
INSERT INTO public.comic_data (upc, issue_number, series, publish_date, image_url, author, artist) VALUES (75960609999300311, 3, 'X-Men (2021)', '09/22/2021', '5/60/6142602cbe0e1', 'Gerry Duggan', 'Pepe Larraz');
INSERT INTO public.comic_data (upc, issue_number, series, publish_date, image_url, author, artist) VALUES (75960609999300511, 5, 'X-Men (2021)', '11/24/2021', '3/80/619e63475a15b', 'Gerry Duggan', 'Ze Carlos');
INSERT INTO public.comic_data (upc, issue_number, series, publish_date, image_url, author, artist) VALUES (75960609999302111, 21, 'X-Men (2021)', '04/12/2023', '6/50/64346a8cda417', 'Gerry Duggan', 'Stefano Caselli');
INSERT INTO public.comic_data (upc, issue_number, series, publish_date, image_url, author, artist) VALUES (75960608332902411, 24, 'Deadpool (2015)', '01/1/2017', '3/c0/586eb66144a83', 'Gerry Duggan', 'Matteo Lolli');
INSERT INTO public.comic_data (upc, issue_number, series, publish_date, image_url, author, artist) VALUES (75960608332903611, 36, 'Deadpool (2015)', '09/13/2017', '8/e0/59b04cb0bb952', 'Gerry Duggan', 'Matteo Lolli');
INSERT INTO public.comic_data (upc, issue_number, series, publish_date, image_url, author, artist) VALUES (75960608332903511, 35, 'Deadpool (2015)', '08/30/2017', '3/b0/59934d239ec11', 'Gerry Duggan', 'Mike Hawthorne');
INSERT INTO public.comic_data (upc, issue_number, series, publish_date, image_url, author, artist) VALUES (75960608332903311, 33, 'Deadpool (2015)', '07/12/2017', '3/b0/595ea832381a7', 'Gerry Duggan', 'Matteo Lolli');
INSERT INTO public.comic_data (upc, issue_number, series, publish_date, image_url, author, artist) VALUES (75960608332903211, 32, 'Deadpool (2015)', '06/14/2017', '6/03/5939931e00a80', 'Gerry Duggan', 'Matteo Lolli');
INSERT INTO public.comic_data (upc, issue_number, series, publish_date, image_url, author, artist) VALUES (75960607909400111, 1, 'Iron Man (2012)', '11/07/2012', '3/90/5a79e06439b05', 'Kieron Gillen', 'Greg Land');
INSERT INTO public.comic_data (upc, issue_number, series, publish_date, image_url, author, artist) VALUES (75960607909401011, 10, 'Iron Man (2012)', '05/15/2013', 'b/e0/5a7b3572f0cac', 'Kieron Gillen', 'Greg Land');
INSERT INTO public.comic_data (upc, issue_number, series, publish_date, image_url, author, artist) VALUES (75960607909402211, 22, 'Iron Man (2012)', '03/05/2014', '6/90/530e47bf870d5', 'Kieron Gillen', 'Paul Rivoche');
INSERT INTO public.comic_data (upc, issue_number, series, publish_date, image_url, author, artist) VALUES (75960607909402311, 23, 'Iron Man (2012)', '03/19/2014', '6/10/52a24d45950dc', 'Kieron Gillen', 'Mike Del Mundo');
INSERT INTO public.comic_data (upc, issue_number, series, publish_date, image_url, author, artist) VALUES (75960607909402811, 28, 'Iron Man (2012)', '06/18/2014', '3/f0/5395d534bb866', 'Kieron Gillen', 'In-Hyuk Lee');

INSERT INTO public.character_data(name) VALUES ('Spider-Man');
INSERT INTO public.character_data(name) VALUES ('Thor');
INSERT INTO public.character_data(name) VALUES ('Darth Vader');
INSERT INTO public.character_data(name) VALUES ('The Hulk');
INSERT INTO public.character_data(name) VALUES ('Captain America');
INSERT INTO public.character_data(name) VALUES ('Ant-Man');
INSERT INTO public.character_data(name) VALUES ('The Wasp');
INSERT INTO public.character_data(name) VALUES ('Dr. Strange');
INSERT INTO public.character_data(name) VALUES ('Wolverine');
INSERT INTO public.character_data(name) VALUES ('Cyclops');
INSERT INTO public.character_data(name) VALUES ('Dr. Doom');
INSERT INTO public.character_data(name) VALUES ('Storm');
INSERT INTO public.character_data(name) VALUES ('Deadpool');
INSERT INTO public.character_data(name) VALUES ('Iron Man');

INSERT INTO public.collection (public, user_id, collection_name) VALUES (true, 1, 'Max''s Collection');
INSERT INTO public.collection (public, user_id, collection_name) VALUES (true, 1, 'Avengers are the BEST');
INSERT INTO public.collection (public, user_id, collection_name) VALUES (true, 1, 'The Spider-Man Collection');
INSERT INTO public.collection (public, user_id, collection_name) VALUES (true, 1, 'X-MEN: ROLLOUT!');
INSERT INTO public.collection (public, user_id, collection_name) VALUES (true, 1, 'Deadpool 4EVER');
INSERT INTO public.collection (public, user_id, collection_name) VALUES (true, 1, 'The Marvel Collection');
INSERT INTO public.collection (public, user_id, collection_name) VALUES (true, 1, 'Iron Man''s BEST Moments');

INSERT INTO public.comic_collection (collection_id, comic_id) VALUES (1, 1);
INSERT INTO public.comic_collection (collection_id, comic_id) VALUES (1, 2);
INSERT INTO public.comic_collection (collection_id, comic_id) VALUES (1, 3);
INSERT INTO public.comic_collection (collection_id, comic_id) VALUES (1, 4);
INSERT INTO public.comic_collection (collection_id, comic_id) VALUES (1, 5);
INSERT INTO public.comic_collection (collection_id, comic_id) VALUES (1, 6);
INSERT INTO public.comic_collection (collection_id, comic_id) VALUES (1, 7);
INSERT INTO public.comic_collection (collection_id, comic_id) VALUES (1, 8);
INSERT INTO public.comic_collection (collection_id, comic_id) VALUES (1, 9);
INSERT INTO public.comic_collection (collection_id, comic_id) VALUES (1, 10);
INSERT INTO public.comic_collection (collection_id, comic_id) VALUES (2, 5);
INSERT INTO public.comic_collection (collection_id, comic_id) VALUES (2, 6);
INSERT INTO public.comic_collection (collection_id, comic_id) VALUES (2, 10);
INSERT INTO public.comic_collection (collection_id, comic_id) VALUES (2, 11);
INSERT INTO public.comic_collection (collection_id, comic_id) VALUES (2, 12);
INSERT INTO public.comic_collection (collection_id, comic_id) VALUES (2, 13);
INSERT INTO public.comic_collection (collection_id, comic_id) VALUES (2, 14);
INSERT INTO public.comic_collection (collection_id, comic_id) VALUES (2, 15);
INSERT INTO public.comic_collection (collection_id, comic_id) VALUES (3, 1);
INSERT INTO public.comic_collection (collection_id, comic_id) VALUES (3, 5);
INSERT INTO public.comic_collection (collection_id, comic_id) VALUES (3, 6);
INSERT INTO public.comic_collection (collection_id, comic_id) VALUES (3, 9);
INSERT INTO public.comic_collection (collection_id, comic_id) VALUES (3, 10);
INSERT INTO public.comic_collection (collection_id, comic_id) VALUES (4, 10);
INSERT INTO public.comic_collection (collection_id, comic_id) VALUES (4, 16);
INSERT INTO public.comic_collection (collection_id, comic_id) VALUES (4, 17);
INSERT INTO public.comic_collection (collection_id, comic_id) VALUES (4, 18);
INSERT INTO public.comic_collection (collection_id, comic_id) VALUES (4, 19);
INSERT INTO public.comic_collection (collection_id, comic_id) VALUES (4, 20);
INSERT INTO public.comic_collection (collection_id, comic_id) VALUES (5, 21);
INSERT INTO public.comic_collection (collection_id, comic_id) VALUES (5, 22);
INSERT INTO public.comic_collection (collection_id, comic_id) VALUES (5, 23);
INSERT INTO public.comic_collection (collection_id, comic_id) VALUES (5, 24);
INSERT INTO public.comic_collection (collection_id, comic_id) VALUES (5, 25);
INSERT INTO public.comic_collection (collection_id, comic_id) VALUES (6, 1);
INSERT INTO public.comic_collection (collection_id, comic_id) VALUES (6, 2);
INSERT INTO public.comic_collection (collection_id, comic_id) VALUES (6, 3);
INSERT INTO public.comic_collection (collection_id, comic_id) VALUES (6, 4);
INSERT INTO public.comic_collection (collection_id, comic_id) VALUES (6, 5);
INSERT INTO public.comic_collection (collection_id, comic_id) VALUES (6, 6);
INSERT INTO public.comic_collection (collection_id, comic_id) VALUES (6, 7);
INSERT INTO public.comic_collection (collection_id, comic_id) VALUES (6, 8);
INSERT INTO public.comic_collection (collection_id, comic_id) VALUES (6, 9);
INSERT INTO public.comic_collection (collection_id, comic_id) VALUES (6, 10);
INSERT INTO public.comic_collection (collection_id, comic_id) VALUES (6, 11);
INSERT INTO public.comic_collection (collection_id, comic_id) VALUES (6, 12);
INSERT INTO public.comic_collection (collection_id, comic_id) VALUES (6, 13);
INSERT INTO public.comic_collection (collection_id, comic_id) VALUES (6, 14);
INSERT INTO public.comic_collection (collection_id, comic_id) VALUES (6, 15);
INSERT INTO public.comic_collection (collection_id, comic_id) VALUES (6, 16);
INSERT INTO public.comic_collection (collection_id, comic_id) VALUES (6, 17);
INSERT INTO public.comic_collection (collection_id, comic_id) VALUES (6, 18);
INSERT INTO public.comic_collection (collection_id, comic_id) VALUES (6, 19);
INSERT INTO public.comic_collection (collection_id, comic_id) VALUES (6, 20);
INSERT INTO public.comic_collection (collection_id, comic_id) VALUES (6, 21);
INSERT INTO public.comic_collection (collection_id, comic_id) VALUES (6, 22);
INSERT INTO public.comic_collection (collection_id, comic_id) VALUES (6, 23);
INSERT INTO public.comic_collection (collection_id, comic_id) VALUES (6, 24);
INSERT INTO public.comic_collection (collection_id, comic_id) VALUES (6, 25);
INSERT INTO public.comic_collection (collection_id, comic_id) VALUES (6, 26);
INSERT INTO public.comic_collection (collection_id, comic_id) VALUES (6, 27);
INSERT INTO public.comic_collection (collection_id, comic_id) VALUES (6, 28);
INSERT INTO public.comic_collection (collection_id, comic_id) VALUES (6, 29);
INSERT INTO public.comic_collection (collection_id, comic_id) VALUES (6, 30);
INSERT INTO public.comic_collection (collection_id, comic_id) VALUES (7, 5);
INSERT INTO public.comic_collection (collection_id, comic_id) VALUES (7, 10);
INSERT INTO public.comic_collection (collection_id, comic_id) VALUES (7, 26);
INSERT INTO public.comic_collection (collection_id, comic_id) VALUES (7, 27);
INSERT INTO public.comic_collection (collection_id, comic_id) VALUES (7, 28);
INSERT INTO public.comic_collection (collection_id, comic_id) VALUES (7, 29);
INSERT INTO public.comic_collection (collection_id, comic_id) VALUES (7, 30);

INSERT INTO public.character_comic(character_id, comic_id) VALUES (1, 1);
INSERT INTO public.character_comic(character_id, comic_id) VALUES (2, 2);
INSERT INTO public.character_comic(character_id, comic_id) VALUES (3, 3);
INSERT INTO public.character_comic(character_id, comic_id) VALUES (4, 4);
INSERT INTO public.character_comic(character_id, comic_id) VALUES (1, 5);
INSERT INTO public.character_comic(character_id, comic_id) VALUES (5, 5);
INSERT INTO public.character_comic(character_id, comic_id) VALUES (2, 6);
INSERT INTO public.character_comic(character_id, comic_id) VALUES (5, 6);
INSERT INTO public.character_comic(character_id, comic_id) VALUES (14, 6);
INSERT INTO public.character_comic(character_id, comic_id) VALUES (6, 7);
INSERT INTO public.character_comic(character_id, comic_id) VALUES (7, 7);
INSERT INTO public.character_comic(character_id, comic_id) VALUES (8, 8);
INSERT INTO public.character_comic(character_id, comic_id) VALUES (1, 9);
INSERT INTO public.character_comic(character_id, comic_id) VALUES (5, 9);
INSERT INTO public.character_comic(character_id, comic_id) VALUES (9, 9);
INSERT INTO public.character_comic(character_id, comic_id) VALUES (12, 9);
INSERT INTO public.character_comic(character_id, comic_id) VALUES (2, 10);
INSERT INTO public.character_comic(character_id, comic_id) VALUES (5, 10);
INSERT INTO public.character_comic(character_id, comic_id) VALUES (14, 10);
INSERT INTO public.character_comic(character_id, comic_id) VALUES (2, 11);
INSERT INTO public.character_comic(character_id, comic_id) VALUES (5, 11);
INSERT INTO public.character_comic(character_id, comic_id) VALUES (11, 11);
INSERT INTO public.character_comic(character_id, comic_id) VALUES (14, 11);
INSERT INTO public.character_comic(character_id, comic_id) VALUES (2, 12);
INSERT INTO public.character_comic(character_id, comic_id) VALUES (5, 12);
INSERT INTO public.character_comic(character_id, comic_id) VALUES (14, 12);
INSERT INTO public.character_comic(character_id, comic_id) VALUES (2, 13);
INSERT INTO public.character_comic(character_id, comic_id) VALUES (5, 13);
INSERT INTO public.character_comic(character_id, comic_id) VALUES (14, 13);
INSERT INTO public.character_comic(character_id, comic_id) VALUES (2, 14);
INSERT INTO public.character_comic(character_id, comic_id) VALUES (5, 14);
INSERT INTO public.character_comic(character_id, comic_id) VALUES (14, 14);
INSERT INTO public.character_comic(character_id, comic_id) VALUES (2, 15);
INSERT INTO public.character_comic(character_id, comic_id) VALUES (5, 15);
INSERT INTO public.character_comic(character_id, comic_id) VALUES (14, 15);
INSERT INTO public.character_comic(character_id, comic_id) VALUES (9, 16);
INSERT INTO public.character_comic(character_id, comic_id) VALUES (10, 16);
INSERT INTO public.character_comic(character_id, comic_id) VALUES (12, 16);
INSERT INTO public.character_comic(character_id, comic_id) VALUES (9, 17);
INSERT INTO public.character_comic(character_id, comic_id) VALUES (10, 17);
INSERT INTO public.character_comic(character_id, comic_id) VALUES (12, 17);
INSERT INTO public.character_comic(character_id, comic_id) VALUES (9, 18);
INSERT INTO public.character_comic(character_id, comic_id) VALUES (10, 18);
INSERT INTO public.character_comic(character_id, comic_id) VALUES (12, 18);
INSERT INTO public.character_comic(character_id, comic_id) VALUES (9, 19);
INSERT INTO public.character_comic(character_id, comic_id) VALUES (10, 19);
INSERT INTO public.character_comic(character_id, comic_id) VALUES (12, 19);
INSERT INTO public.character_comic(character_id, comic_id) VALUES (9, 20);
INSERT INTO public.character_comic(character_id, comic_id) VALUES (10, 20);
INSERT INTO public.character_comic(character_id, comic_id) VALUES (12, 20);
INSERT INTO public.character_comic(character_id, comic_id) VALUES (13, 21);
INSERT INTO public.character_comic(character_id, comic_id) VALUES (13, 22);
INSERT INTO public.character_comic(character_id, comic_id) VALUES (13, 23);
INSERT INTO public.character_comic(character_id, comic_id) VALUES (13, 24);
INSERT INTO public.character_comic(character_id, comic_id) VALUES (13, 25);
INSERT INTO public.character_comic(character_id, comic_id) VALUES (14, 26);
INSERT INTO public.character_comic(character_id, comic_id) VALUES (14, 27);
INSERT INTO public.character_comic(character_id, comic_id) VALUES (14, 28);
INSERT INTO public.character_comic(character_id, comic_id) VALUES (14, 29);
INSERT INTO public.character_comic(character_id, comic_id) VALUES (14, 30);

COMMIT TRANSACTION;
